2021-07-12 10:56:26,831 ERROR: Exception on /item/7 [GET] [in /home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/athomas/Documents/gui/app/main/routes.py", line 333, in item
    'REL_ABUNDANCE'
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 532, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
2021-07-12 10:56:37,506 INFO: PanGIA startup [in /home/athomas/Documents/gui/app/__init__.py:86]
2021-07-12 11:06:15,392 ERROR: Exception on /pangia_vis/2 [GET] [in /home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/athomas/Documents/gui/app/main/routes.py", line 289, in vis_button
    css_resources=INLINE.render_css())
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/flask/templating.py", line 136, in render_template
    ctx.app.update_template_context(context)
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/flask/app.py", line 838, in update_template_context
    context.update(func())
  File "/home/athomas/Documents/gui/app/main/routes.py", line 58, in check_admin
    if 'Admin' in current_user.get_roles():
  File "/home/athomas/miniconda3/envs/gui/lib/python3.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'get_roles'
